#' @title Rush Experiment Registry
#'
#' @description
#' A batchtools-style experiment framework on top of [Rush].
#' Define parameterized problems and algorithms, then cross them with parameter designs
#' to generate experiments that are pushed as tasks into the rush queue.
#'
#' @section Problems:
#' A problem consists of a name, an optional static `data` object, and a function `fun`
#' that generates an instance from the data and problem-specific parameters.
#' The function signature is `fun(data, ...)` where `...` receives the problem parameters.
#'
#' @section Algorithms:
#' An algorithm consists of a name and a function `fun` that takes the problem data,
#' the generated instance, and algorithm-specific parameters, and returns a named list of results.
#' The function signature is `fun(data, instance, ...)` where `...` receives the algorithm parameters.
#'
#' @section Experiments:
#' Experiments are generated by crossing problems with algorithms and their parameter designs.
#' Each combination becomes one task in the rush queue.
#' Call `$add_experiments()` multiple times to extend the design.
#' Workers must be started separately on the `$rush` instance.
#'
#' @export
#' @examples
#' # This example is not executed since Redis must be installed
#' \dontrun{
#'   re = RushExperiment$new()
#'
#'   re$add_problem("sin", fun = function(data, n) {
#'     x = runif(n)
#'     list(x = x, y = sin(x))
#'   })
#'
#'   re$add_algorithm("lm", fun = function(data, instance, degree) {
#'     model = lm(y ~ poly(x, degree), data = instance)
#'     list(rmse = sqrt(mean(model$residuals^2)))
#'   })
#'
#'   keys = re$add_experiments(
#'     prob_designs = list(sin = data.table::data.table(n = c(100, 1000))),
#'     algo_designs = list(lm = data.table::data.table(degree = 1:3)),
#'     repls = 5
#'   )
#'
#'   re$rush$start_local_workers(n_workers = 4)
#'   re$rush$wait_for_workers(4)
#'   re$rush$wait_for_tasks(keys)
#'   re$collect()
#' }
RushExperiment = R6::R6Class("RushExperiment",
  public = list(

    #' @field rush ([Rush])\cr
    #' The underlying Rush instance.
    rush = NULL,

    #' @field problems (named `list()`)\cr
    #' Registered problems. Each element has `fun` and `data`.
    problems = list(),

    #' @field algorithms (named `list()`)\cr
    #' Registered algorithms. Each element has `fun`.
    algorithms = list(),

    #' @description
    #' Creates a new instance of this [R6][R6::R6Class] class.
    #'
    #' @template param_network_id
    #' @template param_config
    #' @param rush ([Rush])\cr
    #' An existing Rush instance.
    #' If provided, `network_id` and `config` are ignored.
    initialize = function(network_id = NULL, config = NULL, rush = NULL) {
      if (!is.null(rush)) {
        assert_class(rush, "Rush")
        self$rush = rush
      } else {
        self$rush = rsh(network_id = network_id, config = config)
      }
    },

    #' @description
    #' Helper for print outputs.
    #'
    #' @param ... (ignored).
    #'
    #' @return (`character()`).
    format = function(...) {
      sprintf("<%s>", class(self)[1L])
    },

    #' @description
    #' Print method.
    #'
    #' @return (`character()`).
    print = function() {
      cat_cli({
        cli::cli_h1("{.cls {class(self)[1L]}}")
        cli::cli_li("Problems: {paste0(names(self$problems), collapse = ', ')}")
        cli::cli_li("Algorithms: {paste0(names(self$algorithms), collapse = ', ')}")
        cli::cli_li("Queued: {self$rush$n_queued_tasks}")
        cli::cli_li("Running: {self$rush$n_running_tasks}")
        cli::cli_li("Finished: {self$rush$n_finished_tasks}")
        cli::cli_li("Failed: {self$rush$n_failed_tasks}")
      })
    },

    #' @description
    #' Add a problem.
    #'
    #' @param name (`character(1)`)\cr
    #' Unique name of the problem.
    #' @param fun (`function(data, ...)`)\cr
    #' Function that generates an instance from `data` and problem parameters.
    #' @param data (any)\cr
    #' Static data object passed to `fun`.
    #' Can be `NULL`.
    add_problem = function(name, fun, data = NULL) {
      assert_string(name)
      assert_function(fun)
      self$problems[[name]] = list(fun = fun, data = data)
      invisible(self)
    },

    #' @description
    #' Add an algorithm.
    #'
    #' @param name (`character(1)`)\cr
    #' Unique name of the algorithm.
    #' @param fun (`function(data, instance, ...)`)\cr
    #' Function that runs the algorithm.
    #' Receives the problem's `data`, the generated `instance`,
    #' and algorithm parameters via `...`.
    #' Must return a named `list()`.
    add_algorithm = function(name, fun) {
      assert_string(name)
      assert_function(fun)
      self$algorithms[[name]] = list(fun = fun)
      invisible(self)
    },

    #' @description
    #' Remove a problem.
    #'
    #' @param name (`character(1)`)\cr
    #' Name of the problem to remove.
    remove_problem = function(name) {
      assert_choice(name, names(self$problems))
      self$problems[[name]] = NULL
      invisible(self)
    },

    #' @description
    #' Remove an algorithm.
    #'
    #' @param name (`character(1)`)\cr
    #' Name of the algorithm to remove.
    remove_algorithm = function(name) {
      assert_choice(name, names(self$algorithms))
      self$algorithms[[name]] = NULL
      invisible(self)
    },

    #' @description
    #' Generate experiments by crossing problems with algorithms and their parameter designs.
    #' Each combination becomes one task in the rush queue.
    #' Also pushes the current set of problems and algorithms as the worker configuration.
    #' Can be called multiple times to extend the design.
    #'
    #' @param prob_designs (named `list()` of `data.frame()`)\cr
    #' Parameter designs for problems.
    #' Names must match registered problems.
    #' Each row defines one set of problem parameters.
    #' If `NULL`, uses all registered problems with no parameters.
    #' @param algo_designs (named `list()` of `data.frame()`)\cr
    #' Parameter designs for algorithms.
    #' Names must match registered algorithms.
    #' Each row defines one set of algorithm parameters.
    #' If `NULL`, uses all registered algorithms with no parameters.
    #' @param repls (`integer(1)`)\cr
    #' Number of replications for each combination.
    #'
    #' @return (`character()`)\cr
    #' Keys of the created tasks (invisibly).
    add_experiments = function(prob_designs = NULL, algo_designs = NULL, repls = 1L) {
      assert_list(prob_designs, types = "data.frame", names = "named", null.ok = TRUE)
      assert_list(algo_designs, types = "data.frame", names = "named", null.ok = TRUE)
      repls = assert_count(repls, positive = TRUE)

      # default: all problems/algorithms with no parameters
      prob_designs = prob_designs %??% set_names(
        lapply(names(self$problems), function(x) data.table()),
        names(self$problems)
      )
      algo_designs = algo_designs %??% set_names(
        lapply(names(self$algorithms), function(x) data.table()),
        names(self$algorithms)
      )

      assert_subset(names(prob_designs), names(self$problems))
      assert_subset(names(algo_designs), names(self$algorithms))

      # push worker config with current problems and algorithms
      self$rush$push_worker_config(
        worker_loop = worker_loop_experiment,
        problems = self$problems,
        algorithms = self$algorithms
      )

      # generate cross product of all experiments
      xss = list()
      for (pn in names(prob_designs)) {
        prob_dt = prob_designs[[pn]]
        prob_rows = if (nrow(prob_dt) == 0) {
          list(list())
        } else {
          lapply(seq_len(nrow(prob_dt)), function(i) as.list(prob_dt[i]))
        }

        for (an in names(algo_designs)) {
          algo_dt = algo_designs[[an]]
          algo_rows = if (nrow(algo_dt) == 0) {
            list(list())
          } else {
            lapply(seq_len(nrow(algo_dt)), function(i) as.list(algo_dt[i]))
          }

          for (pp in prob_rows) {
            for (ap in algo_rows) {
              for (repl in seq_len(repls)) {
                xss[[length(xss) + 1L]] = list(
                  problem = pn,
                  algorithm = an,
                  prob_pars = pp,
                  algo_pars = ap,
                  repl = repl
                )
              }
            }
          }
        }
      }

      lg$info("Pushing %i experiment(s)", length(xss))
      self$rush$push_tasks(xss)
    },

    #' @description
    #' Fetch results of all experiments.
    #'
    #' @return `data.table()` with columns `state`, `xs`, `ys`, `condition`, and `keys`.
    collect = function() {
      self$rush$fetch_tasks_with_state(
        fields = c("xs", "ys", "condition"),
        states = c("finished", "failed")
      )
    }
  )
)
